name: livemicr731-ubuntu
on:
  schedule:
    - cron: '*/50 * * * *' # Run every day at midnight
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget -O authk1.json https://ddd-amer6677.koyeb.app/koyeb01/main/auth.json
          chmod +x /usr/local/bin/OneDriveUploader
          wget -r -np -nd -A json https://ddd-amer6677.koyeb.app/koyeb01/mainn/
          mkdir mainn
          cp *.* mainn
          OneDriveUploader -c authk1.json -s "mainn"
        
          
          
          

    
